#! /bin/sh
#chkconfig:  2345 81 96
#description: start kong

# path: /etc/init.d/kongd
# description: process kong node service
# processname: kongd

SERVICE_USER_NAME=SOFTWARE_USER_NAME
SERVICE_INSTALL_PATH=SOFTWARE_INSTALL_PATH

case "$1" in
    start)
		su - ${SERVICE_USER_NAME}  -c "kong start -c ${SERVICE_INSTALL_PATH}/kong.conf"
    ;;
	stop)
		su - ${SERVICE_USER_NAME}  -c "kong stop"
    ;;
	restart)
	    su - ${SERVICE_USER_NAME}  -c "kong restart -c ${SERVICE_INSTALL_PATH}/kong.conf"
    ;;
	status)
		su - ${SERVICE_USER_NAME}  -c "kong health"
	;;
esac

