#! /bin/sh
#chkconfig:  2345 81 96
#description: start nexus

# path: /etc/init.d/consuld
# description: process consul node service
# processname: consuld

SERVICE_USER_NAME=SOFTWARE_USER_NAME
SERVICE_PROCESS_NAME=consul
SERVICE_INSTALL_PATH=SOFTWARE_INSTALL_PATH

case "$1" in
	start)
		process_id=`ps -ef|grep -i "${SERVICE_PROCESS_NAME} agent" |grep -v "grep"|awk '{print $2}'`
		if [ -z "${process_id}" ];then
        	echo "Starting service..."

            su - ${SERVICE_USER_NAME} -c "nohup ${SERVICE_INSTALL_PATH}/consul agent -config-file=${SERVICE_INSTALL_PATH}/config.json& "
            sleep 10
            process_id=`ps -ef|grep -i "${SERVICE_PROCESS_NAME} agent" |grep -v "grep"|awk '{print $2}'`
            if [ -z "${process_id}" ];then
				echo "Start service error!"
				exit 1
			else
				echo "Start service success!"
			fi
		else
			echo "Service is running!"
		fi
    ;;
	stop)
		echo "Shutting down service..."
		process_id=`ps -ef|grep -i "${SERVICE_PROCESS_NAME} agent" |grep -v "grep"|awk '{print $2}'`
		if [ -z "${process_id}" ];then
	        echo "There is no service running!"
     	else
            kill -9 ${process_id}
            echo "Service " ${process_id} " is killed!"
     	fi
        sleep 5
        echo "Service stop success!"
    ;;
	restart)
        $0 stop
        sleep 5
        $0 start
    ;;
	status)
		process_id=`ps -ef|grep -i "${SERVICE_PROCESS_NAME}" |grep -v "grep"|awk '{print $2}'`
		if [ -z "${process_id}" ];then
			echo "Service is not running!"
			exit 1
		else
			echo "Service is running!"
			exit 0
		fi
	;;
esac

