#! /bin/sh
#chkconfig:  2345 81 96
#description: start alpsconfigserver

# path: /etc/init.d/alpsconfigserverd
# description: process alps micro service
# processname: alpsconfigserverd

SERVICE_PACKAGE_NAME=alpsconfigserver
SERVICE_INSTALL_PATH=SOFTWARE_INSTALL_PATH
SERVICE_USER_NAME=SOFTWARE_USER_NAME
SERVICE_PROCESS_NAME=SOFTWARE_JAR_NAME
SERVICE_JAR_NAME=SOFTWARE_JAR_NAME

case "$1" in
	start)
		process_id=`ps -ef|grep -i "${SERVICE_PROCESS_NAME}" |grep -v "grep"|awk '{print $2}'`
		if [ -z "${process_id}" ];then
			echo "Starting service..."
			
            su - ${SERVICE_USER_NAME} -c "nohup java -jar -Xmx4g -Dconfig.dir=${SERVICE_INSTALL_PATH}/context ${SERVICE_INSTALL_PATH}/${SERVICE_JAR_NAME} --spring.config.location=${SERVICE_INSTALL_PATH}/context/bootstrap.properties 1>/dev/null 2>/dev/null & "
            sleep 10
            process_id=`ps -ef|grep -i "${SERVICE_PROCESS_NAME}" |grep -v "grep"|awk '{print $2}'`
            if [ -z "${process_id}" ];then
				echo "Start service error!"
				exit 1
			else
				echo "Start service success!"
			fi
		else
			echo "Service is running!"
		fi
    ;;
	stop)
		echo "Shutting down service..."
		process_id=`ps -ef|grep -i "${SERVICE_PROCESS_NAME}" |grep -v "grep"|awk '{print $2}'`
		if [ -z "${process_id}" ];then
	        echo "There is no service running!"
     	else
            kill -9 ${process_id}
            echo "Service " ${process_id} " is killed!"
     	fi
        sleep 5
        echo "Service stop success!"
    ;;
	restart)
        $0 stop
        sleep 5
        $0 start
    ;;
	status)
		process_id=`ps -ef|grep -i "${SERVICE_PROCESS_NAME}" |grep -v "grep"|awk '{print $2}'`
		if [ -z "${process_id}" ];then
			echo "Service is not running!"
			exit 1
		else
			echo "Service is running!"
			exit 0
		fi
	;;
esac

